version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: dashly-postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: dashly
      POSTGRES_PASSWORD: dashlypass
      POSTGRES_DB: dashly_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dashly -d dashly_db"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data: 